# Generated by Django 3.1.6 on 2021-05-02 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyRecipeApp', '0002_item_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='text',
            new_name='rIngredients',
        ),
        migrations.AddField(
            model_name='item',
            name='rMainRecipe',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='rName',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='rNameofDish',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='rProcedures',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='recipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='MyRecipeApp.mrecipe'),
        ),
    ]
