# Generated by Django 3.1.6 on 2021-05-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyRecipeApp', '0005_item_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Dish',
        ),
    ]
