# Generated by Django 3.1.6 on 2021-05-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyRecipeApp', '0006_auto_20210502_1059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dish',
            new_name='User',
        ),
    ]
