# Generated by Django 3.1.6 on 2021-05-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyRecipeApp', '0008_auto_20210507_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrecipe',
            name='rDishType',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mrecipe',
            name='rUserName',
            field=models.TextField(default=''),
        ),
    ]
