# Generated by Django 3.1.6 on 2021-05-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyRecipeApp', '0009_auto_20210508_0010'),
        ('MyRecipeApp', '0002_dish_text'),
    ]

    operations = [
    ]
